version: '3.8'

services:
  recruiter-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${RECRUITER_PORT}:${RECRUITER_PORT}"
    env_file:
      - .env
    networks:
      - climbr_network

networks:
  climbr_network:
    driver: bridge
